export const formElements = [
    { name: "title", type: "text", options: [], required: true, hint: "" },
    { name: "designer", type: "text", options: [], required: true, hint: "" },
    {
        name: "description",
        type: "text",
        options: [],
        required: false,
        hint: "",
    },
    {
        name: "craft",
        type: "select",
        options: ["Knitting", "Crochet"],
        required: true,
        hint: "",
    },
    { name: "category", type: "select", options: [
      'Clothing',
      'Accessories',
      'Decor',
      'Amigurumi',
      'Other',
    ], required: true, hint: "" },
    { name: "link URL", type: "text", options: [], required: true, hint: "" },
    { name: "gauge", type: "text", options: [], required: true, hint: "" },
    {
        name: "sizes",
        type: "select",
        options: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL"],
        required: true,
        hint: "",
    },
    {
        name: "yarn weight",
        type: "text",
        options: [],
        required: true,
        hint: "",
    },
    { name: "yardage", type: "text", options: [], required: true, hint: "" },
    {
        name: "needle/hook size",
        type: "text",
        options: [],
        required: true,
        hint: "",
    },
    { name: "price", type: "text", options: [], required: true, hint: "" },
    { name: "languages", type: "text", options: [], required: false, hint: "" },
    { name: "charts", type: "text", options: [], required: false, hint: "" },
    { name: "tags", type: "text", options: [], required: false, hint: "" },
    {
        name: "notes",
        type: "textarea",
        options: [],
        required: false,
        hint: "Add your notes",
    },
]